<script>
    import { page } from '$app/stores'

    const year = new Date().getFullYear()

    const referenceWebs = {
        'https://www.iklubovna.cz': ['iklubovna', 'iKlubovna.cz', 'Children community website'],
        'http://www.niwi.cz': ['niwi', 'Niwi.cz', 'Author\'s personal website'],
        'https://geo.niwi.cz': ['geo', 'GEO symbols', 'Database of Czech geodetic symbols'],
        'https://www.spjf.cz': ['spjf', 'SPJF', 'Children organisation'],
        'https://www.dlouhodobka.cz': ['dlouhodobka', 'Dlouhodobky', 'Long-term games for children teams'],
        'http://obchod.spjf.cz': ['obchod', 'E-shop SPJF', 'SPJF organisation e-shop']
    }
    const tables = [
        'personDetail', 'personRelation', 'personSetting', 'personView',
        'history', 'historyRecord',
    ]

    let webUrl = ''
    $: sql = "--\n\
-- SQL dump of required tables for Gorazd system\n\
-- Generated by script on the page "+$page.url+"\n\
-- Date: "+new Date().toDateString()+"\n\
--\n\
\n\
SET AUTOCOMMIT = 0;\n\
START TRANSACTION;\n\
\n\
\n\
CREATE TABLE `website` (\n\
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n\
    `name` char(255) NOT NULL,\n\
    `protocol` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 means http; 1 https protocol',\n\
    `title` varchar(64) DEFAULT NULL COMMENT 'Title of website will be displayed as the end fragment of each page',\n\
    `systemMail` varchar(64) NOT NULL COMMENT 'System mail for contacting administrators and from which all system e-mails will be send',\n\
    `googleAnalyticsId` varchar(16) DEFAULT NULL COMMENT 'ID from Google Analytics for automatic inclusion of GA measuring code.',\n\
    `controllers` text DEFAULT NULL COMMENT 'Available cotrollers in website (separated by newline). Autogenerated from PageEditor class',\n\
    PRIMARY KEY (`id`),\n\
    UNIQUE KEY `name` (`name`))\n\
    COMMENT='Web section (ex. \"admin.domain.com\")';\n\
\n\
CREATE TABLE `page` (\n\
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n\
    `title` char(255) NOT NULL DEFAULT '',\n\
    `menuTitle` varchar(32) DEFAULT NULL COMMENT 'Short title, used for the menu title etc.',\n\
    `perex` varchar(255) DEFAULT NULL COMMENT 'Short page''s content description.',\n\
    `content` mediumtext DEFAULT NULL,\n\
    `metaDescription` varchar(256) DEFAULT NULL COMMENT 'Page description for META HTML tag',\n\
    `linkOutside` varchar(255) DEFAULT NULL COMMENT 'If this flag is selected, this page ill be redirected to the selected URL',\n\
    `sectionId` int(10) unsigned DEFAULT NULL COMMENT 'Section in which this page belongs',\n\
    `controller` varchar(256) DEFAULT NULL COMMENT 'Path to the controller. NULL means the BasicController',\n\
    `mainController` varchar(256) DEFAULT NULL COMMENT 'Path to the main controller. NULL means dafualt.',\n\
    `readPermission` tinyint(1) unsigned DEFAULT NULL,\n\
    `writePermission` tinyint(1) unsigned DEFAULT NULL,\n\
    `params` varchar(127) DEFAULT NULL COMMENT 'Optional parametres for controllers (Discussion ID etc.)',\n\
    `visible` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Invisible pages aren''t visible in the menu, but they are accessible',\n\
    `accessible` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Inaccessiblee pages aren''t visible in the menu and they aren''t accessible through URL',\n\
    `timestamp` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),\n\
    PRIMARY KEY (`id`),\n\
    KEY `sectionId` (`sectionId`),\n\
    CONSTRAINT `page_ibfk_1` FOREIGN KEY (`sectionId`) REFERENCES `section` (`id`) ON UPDATE CASCADE)\n\
    COMMENT='Pages - URLs (menu items)';\n\
\n\
CREATE TABLE `menuItem` (\n\
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n\
    `pageId` int(10) unsigned NOT NULL,\n\
    `websiteId` int(10) unsigned NOT NULL COMMENT 'Website in wich this page is placed',\n\
    `url` varchar(255) NOT NULL COMMENT 'Path in the website menu structure + name',\n\
    `rank` tinyint(3) NOT NULL DEFAULT 1 COMMENT 'The rank of this page in the list of subitems of the parent menu',\n\
    PRIMARY KEY (`id`),\n\
    UNIQUE KEY `urlOnWebsite` (`url`,`websiteId`),\n\
    KEY `websiteId` (`websiteId`),\n\
    KEY `pageId` (`pageId`),\n\
    CONSTRAINT `menuItem_ibfk_1` FOREIGN KEY (`websiteId`) REFERENCES `website` (`id`) ON UPDATE CASCADE,\n\
    CONSTRAINT `menuItem_ibfk_2` FOREIGN KEY (`pageId`) REFERENCES `page` (`id`) ON UPDATE CASCADE)\n\
    COMMENT='Menu items in the website';\n\
\n\
CREATE TABLE `section` (\n\
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n\
    `name` varchar(32) NOT NULL,\n\
    `description` varchar(512) DEFAULT NULL,\n\
    PRIMARY KEY (`id`))\n\
    COMMENT='Permissions are related to sections. Pages belongs to sections';\n\
\n\
CREATE TABLE `TOK` (\n\
    `key` int(10) unsigned NOT NULL AUTO_INCREMENT,\n\
    `value` varchar(63) NOT NULL,\n\
    `type` char(2) NOT NULL COMMENT 'Bref of the corresponding group',\n\
    PRIMARY KEY (`key`))\n\
    COMMENT='Table of keys';\n\
\n\
CREATE TABLE `person` (\n\
    `pid` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'main person ID in the evidence',\n\
    `name` varchar(127) DEFAULT NULL COMMENT 'Typically surename',\n\
    `secondaryName` varchar(127) DEFAULT NULL COMMENT 'Typically given name',\n\
    `titleBefore` varchar(10) DEFAULT NULL,\n\
    `titleAfter` varchar(10) DEFAULT NULL,\n\
    `email` varchar(127) DEFAULT NULL,\n\
    `type` enum('normal','testing','dummy') NOT NULL DEFAULT 'normal' COMMENT 'Type of the person - normal, testing, dummy',\n\
    `dataSource` int(10) unsigned NOT NULL DEFAULT 50 COMMENT 'Type of data source',\n\
    `sourceWebsite` int(10) unsigned DEFAULT NULL COMMENT 'Web from which was person registered (when dataSource is ''registration'')',\n\
    `insertionDate` datetime NOT NULL,\n\
    `profileViews` int(10) unsigned NOT NULL DEFAULT 0 COMMENT 'Number of views of user''''s profile page',\n\
    `systemState` enum('active','inactive','deleted') NOT NULL DEFAULT 'active' COMMENT 'System state',\n\
    `timestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),\n\
    PRIMARY KEY (`pid`),\n\
    UNIQUE KEY `email` (`email`),\n\
    KEY `name` (`name`,`secondaryName`),\n\
    KEY `dataSource` (`dataSource`),\n\
    KEY `sourceWebsite` (`sourceWebsite`),\n\
    KEY `systemState` (`systemState`),\n\
    CONSTRAINT `person_ibfk_1` FOREIGN KEY (`dataSource`) REFERENCES `TOK` (`key`) ON UPDATE CASCADE,\n\
    CONSTRAINT `person_ibfk_2` FOREIGN KEY (`sourceWebsite`) REFERENCES `website` (`id`) ON UPDATE CASCADE);\n\
\n\
CREATE TABLE `user` (\n\
    `pid` int(10) unsigned NOT NULL,\n\
    `username` char(127) NOT NULL COMMENT 'User login name',\n\
    `urlName` varchar(64) NOT NULL COMMENT 'Unique identifier for URL',\n\
    `password` char(40) DEFAULT NULL COMMENT 'User password',\n\
    `systemPassword` varchar(40) DEFAULT NULL COMMENT 'Password for the system (admin) server',\n\
    `registrationDate` datetime DEFAULT NULL,\n\
    `timestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),\n\
    PRIMARY KEY (`pid`),\n\
    UNIQUE KEY `username` (`username`),\n\
    UNIQUE KEY `urlUsername` (`urlName`),\n\
    CONSTRAINT `user_ibfk_1` FOREIGN KEY (`pid`) REFERENCES `person` (`pid`) ON DELETE NO ACTION ON UPDATE CASCADE) COMMENT='RS user';\n\
\n\
CREATE TABLE `permission` (\n\
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n\
    `pid` int(10) unsigned NOT NULL,\n\
    `sectionId` int(10) unsigned DEFAULT NULL COMMENT 'Superadmin has only one record for all websites automatically',\n\
    `permission` tinyint(1) NOT NULL,\n\
    `timestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),\n\
    PRIMARY KEY (`id`),\n\
    UNIQUE KEY `pid` (`pid`,`sectionId`),\n\
    UNIQUE KEY `pidAndSection` (`pid`,`sectionId`),\n\
    KEY `sectionId` (`sectionId`),\n\
    CONSTRAINT `permission_ibfk_1` FOREIGN KEY (`sectionId`) REFERENCES `section` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,\n\
    CONSTRAINT `permission_ibfk_2` FOREIGN KEY (`pid`) REFERENCES `person` (`pid`) ON DELETE CASCADE ON UPDATE CASCADE);\n\
\n\
CREATE TABLE `visit` (\n\
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID of visit',\n\
    `pid` int(10) unsigned DEFAULT NULL COMMENT 'Person wich has logged-in',\n\
    `realPid` int(10) unsigned DEFAULT NULL COMMENT 'PID of real admin-user who is masked',\n\
    `websiteId` int(10) unsigned NOT NULL,\n\
    `ip` char(41) DEFAULT NULL COMMENT 'IP adress of visit',\n\
    `browser` varchar(255) DEFAULT NULL,\n\
    `timestamp` timestamp NOT NULL DEFAULT current_timestamp() COMMENT 'Time of last page loaded',\n\
    PRIMARY KEY (`id`),\n\
    KEY `sectionId` (`websiteId`)) COMMENT='Table of persons log-ins to the system';\n\
\n\
CREATE TABLE `visitPage` (\n\
    `visitId` int(10) unsigned NOT NULL COMMENT 'Reference visit.id',\n\
    `menuItemId` int(10) unsigned NOT NULL,\n\
    `tailAndSpice` varchar(256) DEFAULT NULL COMMENT 'Meaningful end of URL (tail and spice parameters)',\n\
    `request` text DEFAULT NULL COMMENT 'Dump of GET, POST and SESSION variables',\n\
    `timestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),\n\
    KEY `visitId` (`visitId`),\n\
    CONSTRAINT `visitPage_ibfk_1` FOREIGN KEY (`visitId`) REFERENCES `visit` (`id`) ON DELETE CASCADE ON UPDATE CASCADE);\n\
\n\
CREATE TABLE `visitByDay` (\n\
    `date` date NOT NULL,\n\
    `pageId` int(10) unsigned NOT NULL,\n\
    `visits` int(10) NOT NULL COMMENT 'Visit count',\n\
    PRIMARY KEY (`date`,`pageId`),\n\
    KEY `pageId` (`pageId`),\n\
    KEY `date` (`date`))\n\
    COMMENT='Data cube for page visits by day';\n\
\n\
CREATE TABLE `errorLog` (\n\
    `id` int(10) NOT NULL AUTO_INCREMENT,\n\
    `timestamp` datetime NOT NULL COMMENT 'Date and time of the error',\n\
    `title` tinytext NOT NULL COMMENT 'Error title',\n\
    `detail` tinytext DEFAULT NULL COMMENT 'Other parameter and description',\n\
    `priority` smallint(1) NOT NULL COMMENT '1-lowest, 5-highest',\n\
    `backtrace` text DEFAULT NULL COMMENT 'Calls stack with calling files, lines, classes and functions. Calls in Error and ErrorHandler classes are excluded',\n\
    `queryDump` text NOT NULL COMMENT 'Dump of all queries of this page',\n\
    `request` text DEFAULT NULL COMMENT '$_REQUEST array from PHP',\n\
    `visitId` int(10) unsigned DEFAULT NULL,\n\
    PRIMARY KEY (`id`),\n\
    KEY `visitId` (`visitId`),\n\
    KEY `timestamp` (`timestamp`),\n\
    CONSTRAINT `errorLog_ibfk_1` FOREIGN KEY (`visitId`) REFERENCES `visit` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE);\n\
\n\
CREATE TABLE `error404` (\n\
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n\
    `url` varchar(127) NOT NULL,\n\
    `sectionId` int(10) unsigned NOT NULL,\n\
    `ip` char(41) DEFAULT NULL COMMENT 'IP adress of visit',\n\
    `browser` varchar(255) DEFAULT NULL,\n\
    `timestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),\n\
    PRIMARY KEY (`id`),\n\
    KEY `sectionId` (`sectionId`))\n\
    COMMENT='Logging the 404 error';\n\
\n\
CREATE TABLE `personDetail` (\n\
    `pid` int(10) unsigned NOT NULL DEFAULT 0,\n\
    `correspondentNumber` int(10) unsigned DEFAULT NULL COMMENT 'Dopisovatelske cislo a zaroven ID ze stare databze clenu SPJF',\n\
    `memberNumber` int(10) unsigned DEFAULT NULL COMMENT 'SPJF member number',\n\
    `dateOfBirth` date DEFAULT NULL,\n\
    `sex` enum('M','W') DEFAULT NULL,\n\
    `image` varchar(512) DEFAULT NULL,\n\
    `description` text DEFAULT NULL,\n\
    `nicks` varchar(128) DEFAULT NULL,\n\
    `city` varchar(63) DEFAULT NULL,\n\
    `street` varchar(63) DEFAULT NULL,\n\
    `houseNumber` varchar(7) DEFAULT NULL,\n\
    `zip` varchar(5) DEFAULT NULL COMMENT 'Post code',\n\
    `country` char(3) DEFAULT 'ČR',\n\
    `phone` varchar(16) DEFAULT NULL,\n\
    `facebook` varchar(256) DEFAULT NULL COMMENT 'Facebook address',\n\
    `im` varchar(63) DEFAULT NULL COMMENT 'ICQ or jabber etc.',\n\
    `skype` varchar(31) DEFAULT NULL,\n\
    `website` varchar(127) DEFAULT NULL COMMENT 'Person homepage',\n\
    `secondaryEmail` varchar(128) DEFAULT NULL,\n\
    `BScount` tinyint(4) DEFAULT NULL COMMENT 'Number of BS journals to deliver',\n\
    `BStoDate` date DEFAULT NULL COMMENT 'Date until BS should be delivered (independent from membership)',\n\
    `money` mediumint(7) DEFAULT NULL COMMENT 'Aktualni preplatek',\n\
    `donation` mediumint(7) unsigned DEFAULT NULL COMMENT 'Penezni dar, ktery osoba SPJF venovala',\n\
    `tmpLastVisit` datetime DEFAULT NULL COMMENT 'Las visit date from iKlubovna',\n\
    `tmpClub` int(11) DEFAULT NULL COMMENT 'Club number from old iKlubovna',\n\
    `note` text DEFAULT NULL,\n\
    `timestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),\n\
    PRIMARY KEY (`pid`),\n\
    UNIQUE KEY `memberNumber` (`memberNumber`),\n\
    UNIQUE KEY `correspondentNumber` (`correspondentNumber`),\n\
    CONSTRAINT `personDetail_ibfk_3` FOREIGN KEY (`pid`) REFERENCES `person` (`pid`) ON DELETE CASCADE ON UPDATE CASCADE);\n\
\n\
CREATE TABLE `personRelation` (\n\
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n\
    `pid` int(10) unsigned NOT NULL COMMENT 'When pairing, this should be the column with PID with username',\n\
    `pid2` int(10) unsigned NOT NULL,\n\
    `type` enum('friendship','match','requested') NOT NULL COMMENT 'Type of the relationship',\n\
    `code` char(8) DEFAULT NULL COMMENT 'Code for the pairing transaction',\n\
    PRIMARY KEY (`id`),\n\
    UNIQUE KEY `pid and pid2` (`pid`,`pid2`),\n\
    KEY `pid2` (`pid2`),\n\
    CONSTRAINT `personRelation_ibfk_1` FOREIGN KEY (`pid`) REFERENCES `person` (`pid`) ON UPDATE CASCADE,\n\
    CONSTRAINT `personRelation_ibfk_2` FOREIGN KEY (`pid2`) REFERENCES `person` (`pid`) ON UPDATE CASCADE)\n\
    COMMENT='Relation between accounts of the same person';\n\
\n\
CREATE TABLE `personSetting` (\n\
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n\
    `pid` int(10) unsigned NOT NULL,\n\
    `key` varchar(32) NOT NULL COMMENT 'Setting name',\n\
    `value` text DEFAULT NULL COMMENT 'Setting value',\n\
    PRIMARY KEY (`id`),\n\
    UNIQUE KEY `pidAndKey` (`pid`,`key`),\n\
    KEY `pid` (`pid`),\n\
    CONSTRAINT `personSetting_ibfk_1` FOREIGN KEY (`pid`) REFERENCES `person` (`pid`) ON UPDATE CASCADE)\n\
    COMMENT='Stores personal settings';\n\
CREATE VIEW `personView` AS\n\
    SELECT `p`.`pid` AS `pid`,\n\
    `u`.`username` AS `username`,\n\
    concat_ws(' ',if(`p`.`secondaryName` = '',NULL,`p`.`secondaryName`),if(`p`.`name` = '',NULL,`p`.`name`)) AS `fullName`,\n\
    `p`.`name` AS `name`,\n\
    `p`.`secondaryName` AS `secondaryName`,\n\
    `p`.`titleBefore` AS `titleBefore`,\n\
    `p`.`titleAfter` AS `titleAfter`,\n\
    `p`.`email` AS `email`,\n\
    `t`.`value` AS `dataSource`,\n\
    `w`.`name` AS `sourceWebsite`,\n\
    `p`.`insertionDate` AS `insertionDate`,\n\
    `p`.`profileViews` AS `profileViews`,\n\
    `p`.`systemState` AS `systemState`,\n\
    `d`.`city` AS `city`,\n\
    `d`.`street` AS `street`,\n\
    `d`.`houseNumber` AS `houseNumber`,\n\
    `d`.`zip` AS `zip`,\n\
    `d`.`country` AS `country`,\n\
    `d`.`description` AS `description`,\n\
    `d`.`note` AS `note`,\n\
    `u`.`urlName` AS `urlName`,\n\
    `u`.`registrationDate` AS `registrationDate`,\n\
    `d`.`correspondentNumber` AS `correspondentNumber`,\n\
    `d`.`memberNumber` AS `memberNumber`,\n\
    `d`.`sex` AS `sex`,\n\
    `d`.`dateOfBirth` AS `dateOfBirth`,\n\
    `d`.`nicks` AS `nicks`,\n\
    `d`.`secondaryEmail` AS `secondaryEmail`,\n\
    `d`.`phone` AS `phone`,\n\
    `d`.`facebook` AS `facebook`,\n\
    `d`.`im` AS `im`,\n\
    `d`.`skype` AS `skype`,\n\
    `d`.`website` AS `website`,\n\
    `d`.`image` AS `image`\n\
    FROM\n\
    ((((`person` `p`\n\
    LEFT JOIN `user` `u` on(`p`.`pid` = `u`.`pid`))\n\
    LEFT JOIN `personDetail` `d` on(`p`.`pid` = `d`.`pid`))\n\
    LEFT JOIN `TOK` `t` on(`p`.`dataSource` = `t`.`key`))\n\
    LEFT JOIN `website` `w` on(`p`.`sourceWebsite` = `w`.`id`));\n\
\n\
CREATE TABLE `history` (\n\
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n\
    `type` enum('insert','update','delete') NOT NULL DEFAULT 'insert' COMMENT 'Type of preformed action',\n\
    `table` varchar(31) NOT NULL,\n\
    `recordId` varchar(31) NOT NULL,\n\
    `pid` int(10) unsigned DEFAULT NULL COMMENT 'Person who made this change',\n\
    `datetime` timestamp NOT NULL DEFAULT current_timestamp() COMMENT 'Timestamp of change - but not timestamp of this record!',\n\
    PRIMARY KEY (`id`),\n\
    KEY `table` (`table`))\n\
    COMMENT='Main history table';\n\
\n\
CREATE TABLE `historyRecord` (\n\
    `historyId` int(10) unsigned NOT NULL,\n\
    `column` varchar(31) NOT NULL,\n\
    `value` text DEFAULT NULL,\n\
    UNIQUE KEY `idAndColumn` (`historyId`,`column`),\n\
    KEY `historyId` (`historyId`),\n\
    CONSTRAINT `historyRecord_ibfk_1` FOREIGN KEY (`historyId`) REFERENCES `history` (`id`) ON DELETE CASCADE ON UPDATE CASCADE);\n\
\n\
\n\
-- add website\n\
INSERT INTO `website` (`id`, `name`, `title`)\n\
  VALUES (1, '"+webUrl+"', '"+webUrl+"');\n\
  \n\
-- add the main page\n\
INSERT INTO `page` (`id`, `title`, `content`, `controller`, `readPermission`, `writePermission`)\n\
  VALUES (1,'Homepage', '<p>Welcome on the Homepage!</p>', 'WebAdmin\\\\InitController', 0, 5);\n\
INSERT INTO `menuItem` (`pageId`, `websiteId`, `url`, `rank`)\n\
  VALUES (1, 1, '', 1);\n\
  \n\
-- add MenuController\n\
INSERT INTO `page` (`id`, `title`, `content`, `controller`, `readPermission`, `writePermission`)\n\
   VALUES (2, 'Web structure', 'Menu structure for editing.', 'WebAdmin\\\\MenuController', 5, 5);\n\
INSERT INTO `menuItem` (`pageId`, `websiteId`, `url`, `rank`)\n\
  VALUES (2, 1, 'web-structure', 1);\n\
\n\
COMMIT;\n\
SET AUTOCOMMIT = 1;\n\
"

</script>

<style>
    :global(body) {
        background-color: #333333;
        font-family: Arial, Helvetica, sans-serif;
        color: #CCCCCC;
    }

    #layout {
        margin: 0 auto;
        font-size: 15px;
    }

    #top {
        position: relative;
    }
    #top img {
        max-width: 100%;
        height: auto;
    }
    #top-box {
        position: absolute;
        top: 10%;
        right: 4%;
        text-align: center;
    }
    h1 {
        margin: 0 0 0.2em 0;
        padding: 0;
        font-size: 3.4em; /* fallback */
        font-size: 5.5vw;
        color: #ff9600;
        text-shadow: rgba(1, 1, 1, 0.45) 2px 2px 3px;
    }
    #top-box strong {
        font-size: 1.6em; /* fallback */
        font-size: 2.8vw;
        color: #333333;
    }

    a.links {
        position: absolute;
        padding: 0.3em 0.5em;
        font-size: 2.2em; /* fallback */
        font-size: 4.6vw;
        background-color: rgba(0, 0, 0, 0.33);
        text-decoration: none;
    }
    a.links:hover {
        background-color: rgba(0, 0, 0, 0.7);
    }
    #link-about {
        top: 55%;
        right: 4%;
    }
    #link-install {
        bottom: 10%;
        right: 4%;
    }
    #link-download {
        top: 55%;
        left: 4%;
    }
    #link-references {
        bottom: 10%;
        left: 4%;
    }

    #layout #content {
        background-color: rgba(0, 0, 0, 0.33);
        line-height: 1.5em;
        font-size: 18px;
    }
    #layout #content-inner {
        min-height: 600px;
        padding: .5em 3em 2em 3em;
        background-color: rgba(0, 0, 0, 0.33);
    }

    #layout #footer {
        clear: both;
        padding: 8px;
        background-color: rgba(0, 0, 0, 0.1);
        color: #55a2ef;
    }
    #layout #footer {
        color: #777777;
    }
    #layout #footer a {
        color: #555555;
    }

    /* Style for small devices: right col on the bottom */
    @media (max-width: 440px) {
        #layout {
            width: 440px;
        }
    }
    /* Style for really huge devices: restrict max width */
    @media (min-width: 1200px) {
        #layout {
            width: 1200px;
        }
        h1 {
            font-size: 4.3em;
        }
        #top-box strong {
            font-size: 2.1em;
        }
        a.links {
            font-size: 3.5em;
        }
    }

    /*
    --
    Basic page elements
    --
    */
    h2 {
        margin: 1.3em 0 0.7em 0;
        padding-bottom: 0.2em;
        border-bottom: 2px dotted #555555;
        font-size: 2em;
        color: #c0eb3f;
    }

    a {
        color: #c0eb3f;
    }
    a:hover {
        color: white;
    }

    img {
        max-width: 100%;
        height: auto;
    }
    img#head {
        float: right;
    }
    img#installation {
        float: right;
        opacity: 0.9;
    }
    
    form {
        display: inline-block;
        margin: 1em 0;
        padding: 1em;
        border: 2px dotted white;
        text-align: center;
    }
    pre {
        margin: 0.5em 0;
        padding: 0.5em 1em;
        border: 2px dotted white;
        font-size: 0.6em;
        line-height: 1em;
    }

    /* References */
    .reference-box {
        display: inline-block;
        width: 180px;
        height: 220px;
        margin: 1em;
        padding: 1em;
        border: 3px solid #2A2A2A;
        border-radius: 15px;
        line-height: 1.6em;
        text-align: center;
        vertical-align: top;
        text-decoration: none;
        font-size: 0.8em;
        color: white;
    }
    .reference-box:hover {
        background-color: #2A2A2A;
    }
    .reference-box h3 {
        height: 1.2em;
        margin: 0 0 0.5em 0;
        font-weight: bold;
    }
    .reference-box img {
        width: 150px;
    }
    .reference-box:hover img {
        -webkit-filter: drop-shadow(8px 4px 8px rgba(0,0,0,1.0));
        filter: drop-shadow(8px 4px 8px rgba(0,0,0,1.0));
    }

    .copyright {
        display: inline-block;
        vertical-align: middle;
    }
</style>

<div id="layout">
    <div id="top">
        <img src="/top.jpg" alt="Gorazd system landscape">
        <div id="top-box">
            <h1>Gorazd system</h1>
            <strong>Open-source PHP framework and <abbr title="Content Management System">CMS</abbr></strong>
        </div>
        <a href="#about" class="links" id="link-about">About</a>
        <a href="#installation" class="links" id="link-install">How to install</a>
        <a href="#references" class="links" id="link-references">References</a>
        <a href="#download" class="links" id="link-download">Download</a>
    </div>

    <div id="content">
        <div id="content-inner">

            <h2 id="about">What is Gorazd System?</h2>
            <img alt="Saint Gorazd" src="/gorazd-head.png" id="head">
            Gorazd system is the open-source PHP framework and content management system with following features:
            
            <ul>
                <li>Dynamic website structure and content administration
                <li>Advanced user management - RBAC model, user profile pages...
                <li><em>Forms</em> - complex ORM and GUI toolkit for very customizable administration pages for database tables
                <li>Modules for articles, discussions, e-shop, photo galleries, news, polls, ticketing system, mailing, task scheduling...
                <li>Automatic versionning for all data in the database
                <li>Integrated visitors statistics
                <li><em>Synaum</em> - tool for deploying code to the server
                <li>Active development 2009 - 2018
            </ul>
        
            <h2 id="installation">Installation guide</h2>
            
            <h3>Requirements:</h3>
            
            <ul>
                <li>Apache hosting with enabled mod_rewrite
                <li>PHP 5.3, 5.4, 5.5, 5.6
                <li>MySQL &gt;= 5.0
            </ul>
        
            <img src="/installation.png" alt="Installtion instructions" id="installation">
        
            <h3>Installation step-by-step:</h3>
        
            <ol>
                <li><strong>Getting sources</strong><br>
                Download or clone Gorazd System source files
                <li><strong>Config file</strong><br>
                Modify configuration file config-local.php for your project:
                    <ul>
                        <li>Setup the path to the project root directory on the server
                        <li>Setup the salt variable with some random value. Your and other users passwords will be <a href="https://web.archive.org/web/20220704111132/http://en.wikipedia.org/wiki/Salt_(cryptography)">more safe</a>
                        <li>Setup parameters of MySQL database connection -&nbsp;
                    </ul>
                </li>
                <li><strong>Upload to the server</strong><br>
                Upload all system files from step 1 and config file from step 2 to the server.
                <li><strong>Get SQL init script</strong><br>
                Generate initialisation script for the MySQL database:
                
                <form>
                    <label for="webName">Your website URL for generating SQL:</label>
                    <input type="text" name="webName" maxlength="128" placeholder="www.myweb.com" bind:value={webUrl} />
                </form>

                {#if webUrl}
                    <pre>{sql}</pre>
                {/if}
            </li>
                <li><strong>Initialise the database</strong><br>
                Run the SQL script from the previous step in your MySQL database.</li>
                <li><strong>Create your superadmin account</strong><br>
                Congratulations! The homepage of your project should run now on your domain{#if webUrl}&nbsp;{webUrl}{/if}. Now you should create the superadministrator account. On your homepage, yourproject.com, simply pick your username and password.</li>
                <li><strong>Edit your website</strong><br>
                As an superadminsitrator, you can now edit your website:
                <ul>
                    <li>​​managing pages on <em>{#if webUrl}{webUrl}{:else}yourproject.com{/if}/web-structure</em></li>
                    <li>assigning controllers to your pages will allow you to manage users, tasks, log records, system variables etc.</li>
                </ul>
                </li>
                <li><strong>Website customisation</strong><br>
                Now the real work on your project begins! Create your custom module - simply create the folder with your project name in modules directory.&nbsp;You can get the inspiration for your own module from the source code of this website. You can <a href="https://web.archive.org/web/20220704111132/https://github.com/niwics/gorazd-website">downlaod or clone it&nbsp;from the GitHub</a>.
                <ul>
                    <li>Modify basic HTML web page structure and logic in <em>MainController</em> and <em>MainView</em> files and put them into your module folder to the subfolder php</li>
                    <li>To modify styles, add a custom css files and include them with <em>$this-&gt;addCss('myfile.css')</em> in your Main or another controller. Put the css file into the subfolder css in your module folder</li>
                    <li>If you need a specific functionality, you can create your custom Controller and it to the controllers folder in your module folder.</li>
                </ul>
                </li>
            </ol>
        
            <h2 id="references">Which websites runs on Gorazd System?</h2>
            {#each Object.entries(referenceWebs) as [web, params]}
                <a href={web} class="reference-box">
                    <h3>{params[1]}</h3>
                    <img src="/references/{params[0]}.jpg" alt="Website homepage"><br>{params[2]}
                </a>
            {/each}
            <p>... and several smaller websites.</p>
        
            <h2 id="download">Download</h2>
            <a href="https://github.com/niwics">GitHub - niwics</a>
        
            <h2>Author</h2>
            <a href="http://niwi.cz">Miroslav Kvasnica - niwi</a>
        </div>
    </div>

    <div id="footer">
        <div class="copyright">&copy; <a href="http://www.niwi.cz">niwi</a> {year} |
            <a href="https://gorazd.niwi.cz" title="Redakční systém Gorazd">RS Gorazd</a></div>
    </div>
</div>